name: Pull Request

on:
  pull_request:
    branches: [ dev ]
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request = context.payload.pull_request;

            if (pull_request === undefined) {
              console.log('pull_request is undefined');
              return;
            }

            const body = pull_request.body;
            const title = pull_request.title;

            if (body === undefined || title === undefined) {
              console.log('body or title is undefined');

              await github.rest.issues.createComment({
                issue_number: pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'body or title is undefined'
              });
              await github.rest.issues.addLabels({
                pull_number: pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
              
              return;
            }
